-- 1. Count the number of sales transactions for each product.  
SELECT prod_id, COUNT(*) AS transaction_count
FROM sh.sales
GROUP BY prod_id
  
-- 2. Find the average sale amount for each product.  
SELECT prod_id, avg(amount_sold) as average_sales from sh.SALES
group by PROD_ID
  
-- 3. Find the maximum and minimum sale amount for each product.  
SELECT prod_id, max(amount_sold) as max_sales, min(amount_sold) as min_sales from sh.SALES
group by PROD_ID
  
-- 4. Find the total revenue generated by each product.  
SELECT prod_id, sum(amount_sold) as total_revenue from sh.SALES
group by PROD_ID
  
-- 5. Count the number of sales transactions for each customer.
SELECT cust_id, count(*) as total_sales_trans from sh.SALES
group by CUST_ID
  
-- 6. Find the average sale amount per customer.  
SELECT cust_id, avg(AMOUNT_SOLD) as average_sales from sh.SALES
group by CUST_ID

-- 7. Find the highest purchase amount for each customer.
SELECT cust_id, max(AMOUNT_SOLD) as highest_sales from sh.SALES
group by CUST_ID

-- 8. Find the lowest purchase amount for each customer.
SELECT cust_id, min(AMOUNT_SOLD) as lowest_sales from sh.SALES
group by CUST_ID

-- 9. Find the total revenue generated by each store location.  
-- 10. Count the number of sales transactions for each region.  
-- 11. Find the total revenue per region.  
-- 12. Find the average sale amount per region.  
-- 13. Count the number of sales per month.  
-- 14. Find the total revenue per month.  
-- 15. Find the product that generated the highest revenue.  
-- 16. Find the most frequently purchased product.  
-- 17. Find the most valuable customer based on total spending.  
-- 18. Find the total revenue per sales channel (e.g., online vs. offline).  
-- 19. Count the number of sales for each payment method.  
-- 20. Find the total revenue generated per payment method.
